### ISSUE TITLE
Incompatibility with gcc 8

### ISSUE THREAD

**Issue by Pesa** [martinmoene/scope-lite#12]
Compilation with gcc 8 fails after commit 483f220. The error is:

```
  scope-lite.hpp:831:27: error: invalid use of ‘this’ at top level
           scope_noexcept_op(this->exit_function())
                             ^~~~
```

**Comment by martinmoene** [comment]
Thanks @Pesa, hopefully fixed now.

**Comment by Pesa** [comment]
The error is different now (see below) but it still fails :(
Maybe just drop the `noexcept` altogether for gcc < 9 ?

```
scope-lite.hpp:832:46: error: there are no arguments to ‘exit_function’ that depend on a template parameter, so a declaration of ‘exit_function’ must be available [-fpermissive]
           scope_noexcept_op( scope_noexcept_op(exit_function()) )
                                                ^~~~~~~~~~~~~
[...]
scope-lite.hpp:832:46: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
           scope_noexcept_op( scope_noexcept_op(exit_function()) )
                                                ^~~~~~~~~~~~~
```

**Comment by Pesa** [comment]
Works fine now. Tested with gcc 8 through 13 and clang 7 through 18. Thanks a lot for the quick fix!
